//Base de datas de prueba *Array*.
export const productos = [
    { id: 1, nombre: "Café Colombiano", precio: "$8000", descripcion: "Café premium de origen colombiano.", categoria: "Bebidas", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24490290/CAFE-MOLIDO-523968_a.jpg" },
    { id: 2, nombre: "Arequipe", precio: "$5500", descripcion: "Delicioso dulce de leche, ideal para untar.", categoria: "Dulces", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24648975/Arequipe-Vaso-pote-755132_a.jpg" },
    { id: 3, nombre: "Té Verde", precio: "$7000", descripcion: "Té verde orgánico, excelente para la salud.", categoria: "Bebidas", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24080229/Te-Pina-TOSH-24-gr-3200877_a.jpg" },
    { id: 4, nombre: "Chocolate Amargo", precio: "$10000", descripcion: "Chocolate oscuro con 70% de cacao.", categoria: "Dulces", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24072175/CHOCOLATE-16-PASTILLAS-483614_a.jpg" },
    { id: 5, nombre: "Mermelada de Fresa", precio: "$4500", descripcion: "Mermelada casera de fresas frescas.", categoria: "Dulces", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24115352/Mermelada-Mora-Dp-Practitapa-715336_a.jpg" },
    { id: 6, nombre: "Pan Artesanal", precio: "$3000", descripcion: "Pan hecho a mano con ingredientes naturales.", categoria: "Panadería", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24082040/Pan-Tajado-Artesanal-EXITO-MARCA-PROPIA-500-gr-3297683_a.jpg" },
    { id: 7, nombre: "Queso Manchego", precio: "$12000", descripcion: "Queso español de sabor intenso y textura firme.", categoria: "Lácteos", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24534931/Queso-Mozzarella-Tajado-EXITO-MARCA-PROPIA-400-gr-3280456_a.jpg" },
    { id: 8, nombre: "Yogur Griego", precio: "$6500", descripcion: "Yogur espeso y cremoso, alto en proteínas.", categoria: "Lácteos", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24085881/Yogurt-Griego-Surtido-ZORBA-540-gr-3523327_a.jpg" },
    { id: 9, nombre: "Galletas de Avena", precio: "$3500", descripcion: "Galletas saludables de avena y miel.", categoria: "Dulces", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24074792/Gta-Tosh-Avena-Chocolate-x-180-g-1737491_a.jpg?v=638588578824000000" },
    { id: 10, nombre: "Miel de Abeja", precio: "$9000", descripcion: "Miel pura de abeja, recolectada artesanalmente.", categoria: "Dulces", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24491840/MIEL-LA-ABEJA-DORADA-214880_a.jpg" },
    { id: 11, nombre: "Jugo de Naranja", precio: "$4000", descripcion: "Jugo fresco de naranjas orgánicas.", categoria: "Bebidas", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24648076/Hit-Buenos-Dias-1-Litro-224880_a.jpg" },
    { id: 12, nombre: "Granola", precio: "$5000", descripcion: "Granola crocante con nueces y miel.", categoria: "Cereales", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24068756/Granola-Con-Chocolate-Caja-X-500g-877544_a.jpg" },
    { id: 13, nombre: "Aceite de Oliva", precio: "$15000", descripcion: "Aceite de oliva extra virgen de alta calidad.", categoria: "Aceites", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24447420/Aceite-Oliva-Extravirgen-Organ-TAEQ-500-ml-3259070_a.jpg" },
    { id: 14, nombre: "Jabón Natural", precio: "$3500", descripcion: "Jabón artesanal hecho con ingredientes naturales.", categoria: "Cuidado Personal", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24089112/Jabon-Jardin-Jazmines-Aceite-Almendra-DORADO-330-gr-3406970_a.jpg" },
    { id: 15, nombre: "Turrón de Almendra", precio: "$12000", descripcion: "Turrón español con almendras tostadas.", categoria: "Dulces", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24080669/Almendra-Natural-FRESCAMPO-200-gr-3226878_a.jpg" },
    { id: 16, nombre: "Cerveza Artesanal", precio: "$13000", descripcion: "Cerveza hecha a mano con malta seleccionada.", categoria: "Bebidas", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24487933/Cerveza-Cajica-Miel-Paq-X-4-Und-330ml-C-u-924591_a.jpg" },
    { id: 17, nombre: "Vino Tinto", precio: "$25000", descripcion: "Vino tinto reserva, ideal para acompañar carnes.", categoria: "Bebidas", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24488569/Vino-Tinto-Cabernet-Sauvignon-X-750ml-24281_a.jpg" },
    { id: 18, nombre: "Galletas de Chocolate", precio: "$5000", descripcion: "Galletas crujientes con trozos de chocolate.", categoria: "Dulces", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24853487/Galleta-Dulce-Clasica-CHOKIS-222-Gramo-3013743_a.jpg" },
    { id: 19, nombre: "Leche de Almendra", precio: "$8500", descripcion: "Bebida vegetal de almendras, sin azúcar.", categoria: "Lácteos", imagen: "https://exitocol.vtexassets.com/arquivos/ids/24071297/Forza-Almendra-Original-1429261_a.jpg" },
    { id: 20, nombre: "Té Chai", precio: "$6000", descripcion: "Mezcla de especias para preparar té chai.", categoria: "Bebidas", imagen: "https://exitocol.vtexassets.com/arquivos/ids/22840514/Te-Chai-Con-Especias-TAEQ-100-gr-3482463_a.jpg" }
  ];